---
chat-format: '{WORLD_NAME}:[{PurePerms}][{PREFIX}]<{DISPLAY_NAME}> {MESSAGE}'
if-player-has-no-faction: NoFaction
if-player-has-no-job: unemployed
enable-formatter: true
disablechat: false
default-player-prefix: Default
CustomChat options: '{Kills} | {Deaths} |  [{Money}$]'
CustomJoin: '@Player joined the server ! Iksaku is Awesome'
CustomLeave: '@Player leave the server ! Iksaku is Awesome'
...
