---
chat-format: '{WORLD_NAME}:[{FACTION}][{PurePerms}][{PREFIX}]<{DISPLAY_NAME}> {MESSAGE}'
if-player-has-no-faction: NoFaction
enable-formatter: true
disablechat: false
default-player-prefix: Default
CustomChat options: '{Kills} | {Deaths} | {Money}'
if-player-has-no-job: unemployed
Enable Support Money: false
...
